import Head from 'next/head'
import { HomePage } from '../src/components/home/Home-page'

export default function Home(props) {
  return (
    <div >
      <Head>
        <title>Association Management Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={props.data} />
    </div>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json')
  return {
    props: {
      data: events_categories,
    }
  }
}