import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Association Management Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='styles.header'>
        <nav>
          <Image src="" alt="image" />
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/dashboard'>Dashboard</Link>
          <Link href='/aboutUs'>About Us</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {props.data.map(event => (<Link key={event.id} href={'/events/${event.id'}>
          <Image width={300} height={300} src={event.image} alt={event.title} />
          <h2>{event.title}</h2>
          <p>{event.description}</p>
        </Link>))}
      </main>

      <footer className={styles.footer}>
        <p>Bouchiba-2024 copyrights </p>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json')
  /*const res = await fetch('URL')
  const data = await res.json()
  "Rayen maybe you will need it
  else delete this comment!!!!"*/
  return {
    props: {
      data: events_categories,
    }
  }
}